/* Auto-generated by cbindgen */

#ifndef RUSTCORE_H
#define RUSTCORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct Puzzle16 Puzzle16;

struct Puzzle16 *puzzle_new(uintptr_t _n);

void action(struct Puzzle16 *puz, int32_t op);

bool is_win(struct Puzzle16 *puz);

void puzzle_free(struct Puzzle16 *puz);

#endif  /* RUSTCORE_H */
